=== Tsarionok/Java-Training/XmlParsing/src/main/resources/xml/serials.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns:tns="http://www.training.by/serials"
        xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.training.by/serials"
        elementFormDefault="qualified">

  <element name="entities">
    <complexType>
      <sequence>
        <element ref="tns:entity" minOccurs="1" maxOccurs="unbounded"/>
      </sequence>
    </complexType>
  </element>

  <element name="entity" type="tns:Entity" abstract="true"/>
  <element name="user" type="tns:User" substitutionGroup="tns:entity"/>
  <element name="serial" type="tns:Serial" substitutionGroup="tns:entity"/>

  <complexType name="Entity">
    <sequence>
      <element name="id" type="positiveInteger"/>
    </sequence>
  </complexType>


  <complexType name="User">
    <complexContent>
      <extension base="tns:Entity">
        <sequence>
          <element name="login" type="tns:Login"/>
          <element name="password">
            <simpleType>
              <restriction base="string">
                <pattern value="[a-zA-Z0-9]{5,20}"/>
              </restriction>
            </simpleType>
          </element>
          <element name="user-info" type="tns:UserInfo"/>
        </sequence>
        <attribute name="role" use="optional" default="2">
          <simpleType>
            <restriction base="int">
              <enumeration value="0"></enumeration>
              <enumeration value="1"></enumeration>
              <enumeration value="2"></enumeration>
            </restriction>
          </simpleType>
        </attribute>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="UserInfo">
    <sequence>
      <element name="phone-num" type="string"/>
      <element name="birth-date" type="tns:Birth-date"/>
      <element name="sex">
        <simpleType>
          <restriction base="string">
            <enumeration value="man"></enumeration>
            <enumeration value="woman"></enumeration>
          </restriction>
        </simpleType>
      </element>
    </sequence>
  </complexType>

  <simpleType name="Birth-date">
    <restriction base="date">
      <minExclusive value="01-01-1920"/>
      <maxExclusive value="01-01-2015"/>
    </restriction>
  </simpleType>

  <complexType name="Serial">
    <complexContent>
      <extension base="tns:Entity">
        <sequence>
          <element name="name" type="string"/>
          <element name="premier-date" type="date"/>
          <element name="image-path" type="string"/>
          <element name="description" type="string"/>
          <element name="country" type="string"/>
            <element name="category" type="string"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>

  <simpleType name="Login">
    <restriction base="ID">
      <pattern value="([a-zA-Z])[a-zA-Z0-9]{4,20}"/>
    </restriction>
  </simpleType>

</schema>

=== Tsarionok/Java-Training/XmlParsing/src/main/resources/xml/serials.xml
<?xml version="1.0" encoding="UTF-8"?>
<entities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://www.training.by/serials"
          xsi:schemaLocation="http://www.training.by/serials serials.xsd">
    <user role="1">
        <id>0</id>
        <login>admin</login>
        <password>admin</password>
        <user-info>
            <phone-num>808005553535</phone-num>
            <birth-date>1990-10-11</birth-date>
            <sex>man</sex>
        </user-info>
    </user>

    <serial>
        <id>2</id>
        <name>Сверхъестественное</name>
        <premiere-date>2005-09-13</premiere-date>
        <image_path>supernatural.png</image_path>
        <description>
            Сверхъестественное — мистический сериал, который рассказывает о братьях-охотниках,
            вынужденных истреблять разного рода нечисть в виде демонов, призраков, вампиров и оборотней.
            Сэм и Дин Винчестеры путешествуют по Америке на легендарной Chevrolet Impala 1967 года,
            а явления, с которыми сталкиваются братья, основаны на реальных городских легендах и фольклоре.
        </description>
        <country>США</country>
        <category>Фэнтези</category>
    </serial>

    <user role="2">
        <id>104</id>
        <login>someUser</login>
        <password>pass1234</password>
        <user-info>
            <phone-num>80332220456</phone-num>
            <birth-date>1995-04-06</birth-date>
            <sex>woman</sex>
        </user-info>
    </user>
</entities>
